////////////////////////////////////////////////////////////////////////////////
// Request Struct - Backend proxy API Reference
////////////////////////////////////////////////////////////////////////////////
type AutoGenerated struct {
	Version string  `json:"version"`
	Action  Action  `json:"action"`
	Event   Event   `json:"event"`
	Context Context `json:"context"`
}

type Key struct {
	Type  string `json:"type"`
	Value string `json:"value"`
}

type Parameters struct {
	Key Key `json:"KEY"`
}

type Action struct {
	ActionName string     `json:"actionName"`
	Parameters Parameters `json:"parameters"`
}

type Event struct {
	Type string `json:"type"`
}

type Session struct {
	AccessToken string `json:"accessToken"`
}

type State struct {
}

type Device struct {
	Type  string `json:"type"`
	State State  `json:"state"`
}

type AudioPlayer struct {
	PlayerActivity       string `json:"playerActivity"`
	Token                string `json:"token"`
	OffsetInMilliseconds int    `json:"offsetInMilliseconds"`
}

type SupportedInterfaces struct {
	AudioPlayer AudioPlayer `json:"AudioPlayer"`
}

type PrivatePlay struct {
}

type Context struct {
	Session             Session             `json:"session"`
	Device              Device              `json:"device"`
	SupportedInterfaces SupportedInterfaces `json:"supportedInterfaces"`
	PrivatePlay         PrivatePlay         `json:"privatePlay"`
}

////////////////////////////////////////////////////////////////////////////////
// Response Struct - Backend proxy API Reference
////////////////////////////////////////////////////////////////////////////////

